Update patch set 1
Patch Set 1:

full-eng breaks with the following:

external/libpng/contrib/arm-neon/linux.c:142: error: undefined reference to 'png_read_filter_row_up_neon'
external/libpng/contrib/arm-neon/linux.c:142: error: undefined reference to 'png_read_filter_row_avg4_neon'
external/libpng/contrib/arm-neon/linux.c:142: error: undefined reference to 'png_read_filter_row_paeth4_neon'
external/libpng/contrib/arm-neon/linux.c:142: error: undefined reference to 'png_read_filter_row_sub4_neon'
external/libpng/contrib/arm-neon/linux.c:142: error: undefined reference to 'png_read_filter_row_avg3_neon'
external/libpng/contrib/arm-neon/linux.c:142: error: undefined reference to 'png_read_filter_row_paeth3_neon'
external/libpng/contrib/arm-neon/linux.c:142: error: undefined reference to 'png_read_filter_row_sub3_neon'

Patch-set: 1